# Generated by Django 3.2.4 on 2021-06-22 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatlog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='text',
            new_name='field',
        ),
    ]
