# Generated by Django 3.2.4 on 2021-07-01 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatlog', '0003_chat_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='field',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='author',
            new_name='user',
        ),
    ]
